version: "3.8"

services:
  database:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      - MYSQL_DATABASE=subidentity
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]