CREATE TABLE bounty (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(255),
    value INT(11),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    proposer INT(11) UNSIGNED,
    FOREIGN KEY (proposer) REFERENCES account(id)
)