export enum EventMethod {
    Proposed = "Proposed",
    Awarded = "Awarded",
    BountyProposed = "BountyProposed",
    BountyClaimed = "BountyClaimed",
    ExtrinsicFailed = "ExtrinsicFailed",
    NewTerm = "NewTerm",
    TipRetracted = "TipRetracted",
    NewTip = "NewTip",
    TipClosed = "TipClosed",
    Tabled = "Tabled",
    DemocracyProposed = "DemocracyProposed",
    PreimageNoted = "PreimageNoted",
    Seconded = "Seconded",
    Voted = "Voted",
    Started = "Started",
    Executed = "Executed",
    Passed = "Passed",
    NotPassed = "NotPassed",
    Cancelled = "Cancelled",
    Approved = "Approved",
    Rejected = "Rejected",
    Disapproved = "Disapproved"
}