export enum ExtrinsicMethod {
    PROPOSE = "propose",
    APPROVE = "approve",
    CLOSE = "close",
    EXECUTED = "executed",
    VOTE = "vote",
    SET = "set",
    PROPOSEBOUNTY = "proposeBounty",
    PROPOSESPEND = "proposeSpend",
    PROXY = "proxy",
    PROXY_ANNOUNCED = "proxyAnnounced",
    APPROVEPROPOSAL = "approveProposal",
    ASMULTI = "asMulti",
    CLAIMBOUNTY = "claimBounty",
    RETRACTTIP = "retractTip",
    REPORTAWESOME = "reportAwesome",
    CLOSETIP = "closeTip",
    TIP = "tip",
    BATCHALL = "batchAll",
    BATCH = "batch",
    NOTEPREIMAGE = "notePreimage",
    SECOND = "second",
    NOTEIMMINENTPREIMAGE = "noteImminentPreimage",
    TIPNEW = "tipNew"
}